// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/error.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string          `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Status               int32           `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Title                string          `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Details              []*Error_Detail `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_c21551de19c2604a, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Error) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Error) GetDetails() []*Error_Detail {
	if m != nil {
		return m.Details
	}
	return nil
}

type Error_Detail struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Messages             []string `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error_Detail) Reset()         { *m = Error_Detail{} }
func (m *Error_Detail) String() string { return proto.CompactTextString(m) }
func (*Error_Detail) ProtoMessage()    {}
func (*Error_Detail) Descriptor() ([]byte, []int) {
	return fileDescriptor_c21551de19c2604a, []int{0, 0}
}

func (m *Error_Detail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error_Detail.Unmarshal(m, b)
}
func (m *Error_Detail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error_Detail.Marshal(b, m, deterministic)
}
func (m *Error_Detail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error_Detail.Merge(m, src)
}
func (m *Error_Detail) XXX_Size() int {
	return xxx_messageInfo_Error_Detail.Size(m)
}
func (m *Error_Detail) XXX_DiscardUnknown() {
	xxx_messageInfo_Error_Detail.DiscardUnknown(m)
}

var xxx_messageInfo_Error_Detail proto.InternalMessageInfo

func (m *Error_Detail) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Error_Detail) GetMessages() []string {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "common.Error")
	proto.RegisterType((*Error_Detail)(nil), "common.Error.Detail")
}

func init() { proto.RegisterFile("common/error.proto", fileDescriptor_c21551de19c2604a) }

var fileDescriptor_c21551de19c2604a = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0xc1, 0x4e, 0xc4, 0x20,
	0x10, 0x40, 0xd3, 0x76, 0x5b, 0xdd, 0x31, 0xf1, 0x30, 0xd9, 0x18, 0xb2, 0xa7, 0xc6, 0x8b, 0xf5,
	0x42, 0x13, 0xbd, 0x79, 0x34, 0xfa, 0x03, 0x1c, 0xbd, 0x61, 0x41, 0x76, 0x92, 0x52, 0x36, 0x30,
	0xc6, 0x2f, 0xf4, 0xbf, 0x4c, 0xc1, 0xee, 0x8d, 0xf7, 0x98, 0xf0, 0x18, 0xc0, 0x29, 0x78, 0x1f,
	0x96, 0xd1, 0xc6, 0x18, 0xa2, 0x3c, 0xc7, 0xc0, 0x01, 0xbb, 0xe2, 0xee, 0x7f, 0x2b, 0x68, 0xdf,
	0x57, 0x8f, 0xb7, 0x50, 0x93, 0x11, 0x55, 0x5f, 0x0d, 0x7b, 0x55, 0x93, 0x41, 0x84, 0xdd, 0x14,
	0x8c, 0x15, 0x75, 0x36, 0xf9, 0x8c, 0x77, 0xd0, 0x25, 0xd6, 0xfc, 0x9d, 0x44, 0xd3, 0x57, 0x43,
	0xab, 0xfe, 0x09, 0x0f, 0xd0, 0x32, 0xf1, 0x6c, 0xc5, 0x2e, 0x0f, 0x17, 0x40, 0x09, 0x57, 0xc6,
	0xb2, 0xa6, 0x39, 0x89, 0xb6, 0x6f, 0x86, 0x9b, 0xa7, 0x83, 0x2c, 0x55, 0x99, 0x8b, 0xf2, 0x2d,
	0x5f, 0xaa, 0x6d, 0xe8, 0xf8, 0x02, 0x5d, 0x51, 0xeb, 0x7b, 0x5f, 0x64, 0xe7, 0xed, 0x3b, 0x05,
	0xf0, 0x08, 0xd7, 0xde, 0xa6, 0xa4, 0x9d, 0x4d, 0xa2, 0xee, 0x9b, 0x61, 0xaf, 0x2e, 0xfc, 0xfa,
	0xf8, 0xf1, 0xe0, 0xb5, 0xa3, 0x49, 0x9e, 0x35, 0x9f, 0x74, 0x58, 0x43, 0xe3, 0x42, 0xee, 0xc4,
	0x3f, 0xb4, 0xb8, 0x31, 0xef, 0x3c, 0x96, 0xf8, 0x67, 0x97, 0xe9, 0xf9, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0xfd, 0x03, 0x08, 0x5f, 0x17, 0x01, 0x00, 0x00,
}
