// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fortress/fortress.proto

package fortress

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Document struct {
	List                 []string `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_d949d867b0ff5f59, []int{0}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

type TimeFrame struct {
	Start                int32    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  int32    `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeFrame) Reset()         { *m = TimeFrame{} }
func (m *TimeFrame) String() string { return proto.CompactTextString(m) }
func (*TimeFrame) ProtoMessage()    {}
func (*TimeFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_d949d867b0ff5f59, []int{1}
}

func (m *TimeFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeFrame.Unmarshal(m, b)
}
func (m *TimeFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeFrame.Marshal(b, m, deterministic)
}
func (m *TimeFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeFrame.Merge(m, src)
}
func (m *TimeFrame) XXX_Size() int {
	return xxx_messageInfo_TimeFrame.Size(m)
}
func (m *TimeFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeFrame.DiscardUnknown(m)
}

var xxx_messageInfo_TimeFrame proto.InternalMessageInfo

func (m *TimeFrame) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *TimeFrame) GetEnd() int32 {
	if m != nil {
		return m.End
	}
	return 0
}

type Zone struct {
	PickUp               string   `protobuf:"bytes,1,opt,name=pick_up,json=pickUp,proto3" json:"pick_up,omitempty"`
	Destination          string   `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Zone) Reset()         { *m = Zone{} }
func (m *Zone) String() string { return proto.CompactTextString(m) }
func (*Zone) ProtoMessage()    {}
func (*Zone) Descriptor() ([]byte, []int) {
	return fileDescriptor_d949d867b0ff5f59, []int{2}
}

func (m *Zone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Zone.Unmarshal(m, b)
}
func (m *Zone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Zone.Marshal(b, m, deterministic)
}
func (m *Zone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Zone.Merge(m, src)
}
func (m *Zone) XXX_Size() int {
	return xxx_messageInfo_Zone.Size(m)
}
func (m *Zone) XXX_DiscardUnknown() {
	xxx_messageInfo_Zone.DiscardUnknown(m)
}

var xxx_messageInfo_Zone proto.InternalMessageInfo

func (m *Zone) GetPickUp() string {
	if m != nil {
		return m.PickUp
	}
	return ""
}

func (m *Zone) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type Tie struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	User                 []string `protobuf:"bytes,3,rep,name=user,proto3" json:"user,omitempty"`
	CreatedAt            int64    `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tie) Reset()         { *m = Tie{} }
func (m *Tie) String() string { return proto.CompactTextString(m) }
func (*Tie) ProtoMessage()    {}
func (*Tie) Descriptor() ([]byte, []int) {
	return fileDescriptor_d949d867b0ff5f59, []int{3}
}

func (m *Tie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tie.Unmarshal(m, b)
}
func (m *Tie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tie.Marshal(b, m, deterministic)
}
func (m *Tie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tie.Merge(m, src)
}
func (m *Tie) XXX_Size() int {
	return xxx_messageInfo_Tie.Size(m)
}
func (m *Tie) XXX_DiscardUnknown() {
	xxx_messageInfo_Tie.DiscardUnknown(m)
}

var xxx_messageInfo_Tie proto.InternalMessageInfo

func (m *Tie) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Tie) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Tie) GetUser() []string {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Tie) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Tie) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type Campaign struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Partner              string   `protobuf:"bytes,4,opt,name=partner,proto3" json:"partner,omitempty"`
	BurnSharing          float64  `protobuf:"fixed64,5,opt,name=burn_sharing,json=burnSharing,proto3" json:"burn_sharing,omitempty"`
	Budget               int64    `protobuf:"varint,6,opt,name=budget,proto3" json:"budget,omitempty"`
	Status               string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	AllUsers             bool     `protobuf:"varint,8,opt,name=all_users,json=allUsers,proto3" json:"all_users,omitempty"`
	Ties                 []string `protobuf:"bytes,9,rep,name=ties,proto3" json:"ties,omitempty"`
	CreatedAt            int64    `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Campaign) Reset()         { *m = Campaign{} }
func (m *Campaign) String() string { return proto.CompactTextString(m) }
func (*Campaign) ProtoMessage()    {}
func (*Campaign) Descriptor() ([]byte, []int) {
	return fileDescriptor_d949d867b0ff5f59, []int{4}
}

func (m *Campaign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Campaign.Unmarshal(m, b)
}
func (m *Campaign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Campaign.Marshal(b, m, deterministic)
}
func (m *Campaign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Campaign.Merge(m, src)
}
func (m *Campaign) XXX_Size() int {
	return xxx_messageInfo_Campaign.Size(m)
}
func (m *Campaign) XXX_DiscardUnknown() {
	xxx_messageInfo_Campaign.DiscardUnknown(m)
}

var xxx_messageInfo_Campaign proto.InternalMessageInfo

func (m *Campaign) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Campaign) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Campaign) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Campaign) GetPartner() string {
	if m != nil {
		return m.Partner
	}
	return ""
}

func (m *Campaign) GetBurnSharing() float64 {
	if m != nil {
		return m.BurnSharing
	}
	return 0
}

func (m *Campaign) GetBudget() int64 {
	if m != nil {
		return m.Budget
	}
	return 0
}

func (m *Campaign) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Campaign) GetAllUsers() bool {
	if m != nil {
		return m.AllUsers
	}
	return false
}

func (m *Campaign) GetTies() []string {
	if m != nil {
		return m.Ties
	}
	return nil
}

func (m *Campaign) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Campaign) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type Promo struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CampaignId           string       `protobuf:"bytes,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Type                 string       `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Title                string       `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Slug                 string       `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	Service              string       `protobuf:"bytes,6,opt,name=service,proto3" json:"service,omitempty"`
	AllowedPaymentTypes  []string     `protobuf:"bytes,7,rep,name=allowed_payment_types,json=allowedPaymentTypes,proto3" json:"allowed_payment_types,omitempty"`
	Percentage           float64      `protobuf:"fixed64,8,opt,name=percentage,proto3" json:"percentage,omitempty"`
	UsageLimit           int32        `protobuf:"varint,9,opt,name=usage_limit,json=usageLimit,proto3" json:"usage_limit,omitempty"`
	MaxAmount            int64        `protobuf:"varint,10,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	TimeFrame            []*TimeFrame `protobuf:"bytes,11,rep,name=time_frame,json=timeFrame,proto3" json:"time_frame,omitempty"`
	AllowedCities        []string     `protobuf:"bytes,12,rep,name=allowed_cities,json=allowedCities,proto3" json:"allowed_cities,omitempty"`
	Zones                []*Zone      `protobuf:"bytes,13,rep,name=zones,proto3" json:"zones,omitempty"`
	Priority             int32        `protobuf:"varint,14,opt,name=priority,proto3" json:"priority,omitempty"`
	StartTime            int64        `protobuf:"varint,15,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64        `protobuf:"varint,16,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Vendor               string       `protobuf:"bytes,17,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Provider             string       `protobuf:"bytes,18,opt,name=provider,proto3" json:"provider,omitempty"`
	Category             string       `protobuf:"bytes,19,opt,name=category,proto3" json:"category,omitempty"`
	Item                 string       `protobuf:"bytes,20,opt,name=item,proto3" json:"item,omitempty"`
	CreatedAt            int64        `protobuf:"varint,21,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64        `protobuf:"varint,22,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Promo) Reset()         { *m = Promo{} }
func (m *Promo) String() string { return proto.CompactTextString(m) }
func (*Promo) ProtoMessage()    {}
func (*Promo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d949d867b0ff5f59, []int{5}
}

func (m *Promo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Promo.Unmarshal(m, b)
}
func (m *Promo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Promo.Marshal(b, m, deterministic)
}
func (m *Promo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Promo.Merge(m, src)
}
func (m *Promo) XXX_Size() int {
	return xxx_messageInfo_Promo.Size(m)
}
func (m *Promo) XXX_DiscardUnknown() {
	xxx_messageInfo_Promo.DiscardUnknown(m)
}

var xxx_messageInfo_Promo proto.InternalMessageInfo

func (m *Promo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Promo) GetCampaignId() string {
	if m != nil {
		return m.CampaignId
	}
	return ""
}

func (m *Promo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Promo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Promo) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Promo) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Promo) GetAllowedPaymentTypes() []string {
	if m != nil {
		return m.AllowedPaymentTypes
	}
	return nil
}

func (m *Promo) GetPercentage() float64 {
	if m != nil {
		return m.Percentage
	}
	return 0
}

func (m *Promo) GetUsageLimit() int32 {
	if m != nil {
		return m.UsageLimit
	}
	return 0
}

func (m *Promo) GetMaxAmount() int64 {
	if m != nil {
		return m.MaxAmount
	}
	return 0
}

func (m *Promo) GetTimeFrame() []*TimeFrame {
	if m != nil {
		return m.TimeFrame
	}
	return nil
}

func (m *Promo) GetAllowedCities() []string {
	if m != nil {
		return m.AllowedCities
	}
	return nil
}

func (m *Promo) GetZones() []*Zone {
	if m != nil {
		return m.Zones
	}
	return nil
}

func (m *Promo) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Promo) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Promo) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Promo) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *Promo) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Promo) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Promo) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *Promo) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Promo) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type Discount struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CampaignId           string       `protobuf:"bytes,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Title                string       `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Slug                 string       `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Service              string       `protobuf:"bytes,5,opt,name=service,proto3" json:"service,omitempty"`
	AllowedPaymentTypes  []string     `protobuf:"bytes,6,rep,name=allowed_payment_types,json=allowedPaymentTypes,proto3" json:"allowed_payment_types,omitempty"`
	Percentage           float64      `protobuf:"fixed64,7,opt,name=percentage,proto3" json:"percentage,omitempty"`
	UsageLimit           int32        `protobuf:"varint,8,opt,name=usage_limit,json=usageLimit,proto3" json:"usage_limit,omitempty"`
	MaxAmount            int64        `protobuf:"varint,9,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	TimeFrame            []*TimeFrame `protobuf:"bytes,10,rep,name=time_frame,json=timeFrame,proto3" json:"time_frame,omitempty"`
	AllowedCities        []string     `protobuf:"bytes,11,rep,name=allowed_cities,json=allowedCities,proto3" json:"allowed_cities,omitempty"`
	Zones                []*Zone      `protobuf:"bytes,12,rep,name=zones,proto3" json:"zones,omitempty"`
	Priority             int32        `protobuf:"varint,13,opt,name=priority,proto3" json:"priority,omitempty"`
	StartTime            int64        `protobuf:"varint,14,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64        `protobuf:"varint,15,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Vendor               string       `protobuf:"bytes,16,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Provider             string       `protobuf:"bytes,17,opt,name=provider,proto3" json:"provider,omitempty"`
	Category             string       `protobuf:"bytes,18,opt,name=category,proto3" json:"category,omitempty"`
	Item                 string       `protobuf:"bytes,19,opt,name=item,proto3" json:"item,omitempty"`
	CreatedAt            int64        `protobuf:"varint,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64        `protobuf:"varint,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Discount) Reset()         { *m = Discount{} }
func (m *Discount) String() string { return proto.CompactTextString(m) }
func (*Discount) ProtoMessage()    {}
func (*Discount) Descriptor() ([]byte, []int) {
	return fileDescriptor_d949d867b0ff5f59, []int{6}
}

func (m *Discount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Discount.Unmarshal(m, b)
}
func (m *Discount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Discount.Marshal(b, m, deterministic)
}
func (m *Discount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Discount.Merge(m, src)
}
func (m *Discount) XXX_Size() int {
	return xxx_messageInfo_Discount.Size(m)
}
func (m *Discount) XXX_DiscardUnknown() {
	xxx_messageInfo_Discount.DiscardUnknown(m)
}

var xxx_messageInfo_Discount proto.InternalMessageInfo

func (m *Discount) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Discount) GetCampaignId() string {
	if m != nil {
		return m.CampaignId
	}
	return ""
}

func (m *Discount) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Discount) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Discount) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Discount) GetAllowedPaymentTypes() []string {
	if m != nil {
		return m.AllowedPaymentTypes
	}
	return nil
}

func (m *Discount) GetPercentage() float64 {
	if m != nil {
		return m.Percentage
	}
	return 0
}

func (m *Discount) GetUsageLimit() int32 {
	if m != nil {
		return m.UsageLimit
	}
	return 0
}

func (m *Discount) GetMaxAmount() int64 {
	if m != nil {
		return m.MaxAmount
	}
	return 0
}

func (m *Discount) GetTimeFrame() []*TimeFrame {
	if m != nil {
		return m.TimeFrame
	}
	return nil
}

func (m *Discount) GetAllowedCities() []string {
	if m != nil {
		return m.AllowedCities
	}
	return nil
}

func (m *Discount) GetZones() []*Zone {
	if m != nil {
		return m.Zones
	}
	return nil
}

func (m *Discount) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Discount) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Discount) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Discount) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *Discount) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Discount) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Discount) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *Discount) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Discount) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type Cashback struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string       `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CampaignId           string       `protobuf:"bytes,3,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Description          string       `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	AllowedPaymentTypes  []string     `protobuf:"bytes,5,rep,name=allowed_payment_types,json=allowedPaymentTypes,proto3" json:"allowed_payment_types,omitempty"`
	Service              string       `protobuf:"bytes,6,opt,name=service,proto3" json:"service,omitempty"`
	Percentage           int64        `protobuf:"varint,7,opt,name=percentage,proto3" json:"percentage,omitempty"`
	MaxAmount            int64        `protobuf:"varint,8,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	TimeFrame            []*TimeFrame `protobuf:"bytes,9,rep,name=time_frame,json=timeFrame,proto3" json:"time_frame,omitempty"`
	AllowedCities        []string     `protobuf:"bytes,10,rep,name=allowed_cities,json=allowedCities,proto3" json:"allowed_cities,omitempty"`
	UsageLimit           int64        `protobuf:"varint,11,opt,name=usage_limit,json=usageLimit,proto3" json:"usage_limit,omitempty"`
	Zones                []*Zone      `protobuf:"bytes,12,rep,name=zones,proto3" json:"zones,omitempty"`
	Priority             int32        `protobuf:"varint,13,opt,name=priority,proto3" json:"priority,omitempty"`
	Status               string       `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            int64        `protobuf:"varint,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64        `protobuf:"varint,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Cashback) Reset()         { *m = Cashback{} }
func (m *Cashback) String() string { return proto.CompactTextString(m) }
func (*Cashback) ProtoMessage()    {}
func (*Cashback) Descriptor() ([]byte, []int) {
	return fileDescriptor_d949d867b0ff5f59, []int{7}
}

func (m *Cashback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cashback.Unmarshal(m, b)
}
func (m *Cashback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cashback.Marshal(b, m, deterministic)
}
func (m *Cashback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cashback.Merge(m, src)
}
func (m *Cashback) XXX_Size() int {
	return xxx_messageInfo_Cashback.Size(m)
}
func (m *Cashback) XXX_DiscardUnknown() {
	xxx_messageInfo_Cashback.DiscardUnknown(m)
}

var xxx_messageInfo_Cashback proto.InternalMessageInfo

func (m *Cashback) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Cashback) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Cashback) GetCampaignId() string {
	if m != nil {
		return m.CampaignId
	}
	return ""
}

func (m *Cashback) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Cashback) GetAllowedPaymentTypes() []string {
	if m != nil {
		return m.AllowedPaymentTypes
	}
	return nil
}

func (m *Cashback) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Cashback) GetPercentage() int64 {
	if m != nil {
		return m.Percentage
	}
	return 0
}

func (m *Cashback) GetMaxAmount() int64 {
	if m != nil {
		return m.MaxAmount
	}
	return 0
}

func (m *Cashback) GetTimeFrame() []*TimeFrame {
	if m != nil {
		return m.TimeFrame
	}
	return nil
}

func (m *Cashback) GetAllowedCities() []string {
	if m != nil {
		return m.AllowedCities
	}
	return nil
}

func (m *Cashback) GetUsageLimit() int64 {
	if m != nil {
		return m.UsageLimit
	}
	return 0
}

func (m *Cashback) GetZones() []*Zone {
	if m != nil {
		return m.Zones
	}
	return nil
}

func (m *Cashback) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Cashback) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Cashback) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Cashback) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type AppliedPromo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PromoId              string   `protobuf:"bytes,3,opt,name=promo_id,json=promoId,proto3" json:"promo_id,omitempty"`
	Service              string   `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Used                 int32    `protobuf:"varint,5,opt,name=used,proto3" json:"used,omitempty"`
	Code                 string   `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	AppliedAt            int64    `protobuf:"varint,7,opt,name=applied_at,json=appliedAt,proto3" json:"applied_at,omitempty"`
	CreatedAt            int64    `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppliedPromo) Reset()         { *m = AppliedPromo{} }
func (m *AppliedPromo) String() string { return proto.CompactTextString(m) }
func (*AppliedPromo) ProtoMessage()    {}
func (*AppliedPromo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d949d867b0ff5f59, []int{8}
}

func (m *AppliedPromo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppliedPromo.Unmarshal(m, b)
}
func (m *AppliedPromo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppliedPromo.Marshal(b, m, deterministic)
}
func (m *AppliedPromo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppliedPromo.Merge(m, src)
}
func (m *AppliedPromo) XXX_Size() int {
	return xxx_messageInfo_AppliedPromo.Size(m)
}
func (m *AppliedPromo) XXX_DiscardUnknown() {
	xxx_messageInfo_AppliedPromo.DiscardUnknown(m)
}

var xxx_messageInfo_AppliedPromo proto.InternalMessageInfo

func (m *AppliedPromo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AppliedPromo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AppliedPromo) GetPromoId() string {
	if m != nil {
		return m.PromoId
	}
	return ""
}

func (m *AppliedPromo) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *AppliedPromo) GetUsed() int32 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *AppliedPromo) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *AppliedPromo) GetAppliedAt() int64 {
	if m != nil {
		return m.AppliedAt
	}
	return 0
}

func (m *AppliedPromo) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *AppliedPromo) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type Estimation struct {
	ActualAmount         int64    `protobuf:"varint,1,opt,name=actual_amount,json=actualAmount,proto3" json:"actual_amount,omitempty"`
	DiscountedAmount     int64    `protobuf:"varint,2,opt,name=discounted_amount,json=discountedAmount,proto3" json:"discounted_amount,omitempty"`
	AppliedCode          string   `protobuf:"bytes,3,opt,name=applied_code,json=appliedCode,proto3" json:"applied_code,omitempty"`
	RewardType           string   `protobuf:"bytes,4,opt,name=reward_type,json=rewardType,proto3" json:"reward_type,omitempty"`
	RewardId             string   `protobuf:"bytes,5,opt,name=reward_id,json=rewardId,proto3" json:"reward_id,omitempty"`
	PaymentChannel       string   `protobuf:"bytes,6,opt,name=payment_channel,json=paymentChannel,proto3" json:"payment_channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Estimation) Reset()         { *m = Estimation{} }
func (m *Estimation) String() string { return proto.CompactTextString(m) }
func (*Estimation) ProtoMessage()    {}
func (*Estimation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d949d867b0ff5f59, []int{9}
}

func (m *Estimation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Estimation.Unmarshal(m, b)
}
func (m *Estimation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Estimation.Marshal(b, m, deterministic)
}
func (m *Estimation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Estimation.Merge(m, src)
}
func (m *Estimation) XXX_Size() int {
	return xxx_messageInfo_Estimation.Size(m)
}
func (m *Estimation) XXX_DiscardUnknown() {
	xxx_messageInfo_Estimation.DiscardUnknown(m)
}

var xxx_messageInfo_Estimation proto.InternalMessageInfo

func (m *Estimation) GetActualAmount() int64 {
	if m != nil {
		return m.ActualAmount
	}
	return 0
}

func (m *Estimation) GetDiscountedAmount() int64 {
	if m != nil {
		return m.DiscountedAmount
	}
	return 0
}

func (m *Estimation) GetAppliedCode() string {
	if m != nil {
		return m.AppliedCode
	}
	return ""
}

func (m *Estimation) GetRewardType() string {
	if m != nil {
		return m.RewardType
	}
	return ""
}

func (m *Estimation) GetRewardId() string {
	if m != nil {
		return m.RewardId
	}
	return ""
}

func (m *Estimation) GetPaymentChannel() string {
	if m != nil {
		return m.PaymentChannel
	}
	return ""
}

func init() {
	proto.RegisterType((*Document)(nil), "fortress.Document")
	proto.RegisterType((*TimeFrame)(nil), "fortress.TimeFrame")
	proto.RegisterType((*Zone)(nil), "fortress.Zone")
	proto.RegisterType((*Tie)(nil), "fortress.Tie")
	proto.RegisterType((*Campaign)(nil), "fortress.Campaign")
	proto.RegisterType((*Promo)(nil), "fortress.Promo")
	proto.RegisterType((*Discount)(nil), "fortress.Discount")
	proto.RegisterType((*Cashback)(nil), "fortress.Cashback")
	proto.RegisterType((*AppliedPromo)(nil), "fortress.AppliedPromo")
	proto.RegisterType((*Estimation)(nil), "fortress.Estimation")
}

func init() { proto.RegisterFile("fortress/fortress.proto", fileDescriptor_d949d867b0ff5f59) }

var fileDescriptor_d949d867b0ff5f59 = []byte{
	// 1032 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x96, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0xc7, 0xe1, 0xc8, 0xb2, 0xa5, 0x63, 0xc7, 0x71, 0x99, 0x2f, 0x6d, 0x43, 0x5b, 0xd7, 0xdb,
	0x30, 0x0f, 0x05, 0x12, 0x20, 0x7d, 0x02, 0x2f, 0xdd, 0x80, 0x00, 0xbb, 0x28, 0xb4, 0xf4, 0xa6,
	0x37, 0x02, 0x23, 0xb2, 0x36, 0x51, 0x7d, 0x81, 0xa2, 0x92, 0x66, 0xc0, 0xde, 0x60, 0x97, 0xbb,
	0x1d, 0xb0, 0xc7, 0xdb, 0xed, 0xde, 0x60, 0x38, 0xa4, 0x24, 0xdb, 0x4a, 0xac, 0x7a, 0xdd, 0x1d,
	0xcf, 0xff, 0x88, 0xd2, 0xe1, 0x9f, 0xbf, 0x23, 0x12, 0x4e, 0xdf, 0xa7, 0x52, 0x49, 0x9e, 0xe7,
	0xe7, 0xd5, 0xe0, 0x2c, 0x93, 0xa9, 0x4a, 0x89, 0x53, 0xc5, 0xd3, 0x67, 0xe0, 0xbc, 0x4e, 0xc3,
	0x22, 0xe6, 0x89, 0x22, 0x04, 0xba, 0x91, 0xc8, 0x95, 0xd7, 0x99, 0x58, 0x33, 0xd7, 0xd7, 0xe3,
	0xe9, 0x2b, 0x70, 0xaf, 0x45, 0xcc, 0x7f, 0x92, 0x34, 0xe6, 0xe4, 0x08, 0xec, 0x5c, 0x51, 0x89,
	0x4f, 0x74, 0x66, 0xb6, 0x6f, 0x02, 0x32, 0x06, 0x8b, 0x27, 0xcc, 0xdb, 0xd3, 0x1a, 0x0e, 0xa7,
	0x73, 0xe8, 0xbe, 0x4b, 0x13, 0x4e, 0x4e, 0xa1, 0x9f, 0x89, 0xf0, 0x43, 0x50, 0x64, 0x7a, 0x86,
	0xeb, 0xf7, 0x30, 0x7c, 0x9b, 0x91, 0x09, 0x0c, 0x18, 0xcf, 0x95, 0x48, 0xa8, 0x12, 0x69, 0xa2,
	0xa7, 0xba, 0xfe, 0xba, 0x34, 0xfd, 0x0d, 0xac, 0x6b, 0xc1, 0xc9, 0x08, 0xf6, 0x04, 0x2b, 0x27,
	0xef, 0x09, 0x86, 0x15, 0x28, 0xa1, 0x22, 0x5e, 0x4e, 0x31, 0x01, 0x16, 0x5e, 0xe4, 0x5c, 0x7a,
	0x96, 0x29, 0x1c, 0xc7, 0xe4, 0x29, 0x40, 0x28, 0x39, 0x55, 0x9c, 0x05, 0x54, 0x79, 0xdd, 0x49,
	0x67, 0x66, 0xf9, 0x6e, 0xa9, 0xcc, 0x15, 0xa6, 0x8b, 0x8c, 0x55, 0x69, 0xdb, 0xa4, 0x4b, 0x65,
	0xae, 0xa6, 0x7f, 0xed, 0x81, 0x73, 0x49, 0xe3, 0x8c, 0x8a, 0x45, 0xb2, 0x7b, 0x11, 0x61, 0xca,
	0xb8, 0x67, 0x69, 0x51, 0x8f, 0x89, 0x07, 0xfd, 0x8c, 0x4a, 0x95, 0x70, 0xa9, 0x2b, 0x70, 0xfd,
	0x2a, 0x24, 0x2f, 0x60, 0x78, 0x53, 0xc8, 0x24, 0xc8, 0x97, 0x54, 0x8a, 0x64, 0xa1, 0x2b, 0xe8,
	0xf8, 0x03, 0xd4, 0x7e, 0x31, 0x12, 0x39, 0x81, 0xde, 0x4d, 0xc1, 0x16, 0x5c, 0x79, 0x3d, 0x5d,
	0x5e, 0x19, 0xa1, 0x9e, 0x2b, 0xaa, 0x8a, 0xdc, 0xeb, 0x1b, 0x53, 0x4d, 0x44, 0xbe, 0x02, 0x97,
	0x46, 0x51, 0x80, 0xab, 0xcf, 0x3d, 0x67, 0xd2, 0x99, 0x39, 0xbe, 0x43, 0xa3, 0xe8, 0x2d, 0xc6,
	0x58, 0x9d, 0x12, 0x3c, 0xf7, 0x5c, 0x63, 0x11, 0x8e, 0x1b, 0x16, 0x41, 0xbb, 0x45, 0x83, 0xa6,
	0x45, 0x7f, 0xda, 0x60, 0xbf, 0x91, 0x69, 0x9c, 0x3e, 0xf0, 0xe7, 0x39, 0x0c, 0xc2, 0xd2, 0xbb,
	0x40, 0xb0, 0xd2, 0x25, 0xa8, 0xa4, 0x2b, 0xa6, 0x8b, 0xb9, 0xcf, 0x6a, 0xab, 0x70, 0xbc, 0x32,
	0xb5, 0xdb, 0x30, 0x35, 0x8f, 0x0a, 0x63, 0x8f, 0xeb, 0xeb, 0x31, 0x9a, 0x9a, 0x73, 0x79, 0x2b,
	0x42, 0xae, 0x8d, 0x71, 0xfd, 0x2a, 0x24, 0x17, 0x70, 0x4c, 0xa3, 0x28, 0xbd, 0xe3, 0x2c, 0xc8,
	0xe8, 0x3d, 0x32, 0x1d, 0xe0, 0xbb, 0xd1, 0x28, 0x5c, 0xf5, 0x61, 0x99, 0x7c, 0x63, 0x72, 0xd7,
	0x98, 0x22, 0xcf, 0x00, 0x32, 0x2e, 0x43, 0x9e, 0x28, 0xba, 0xe0, 0xda, 0xb6, 0x8e, 0xbf, 0xa6,
	0xe0, 0x62, 0x8a, 0x9c, 0x2e, 0x78, 0x10, 0x89, 0x58, 0x28, 0xcf, 0xd5, 0x94, 0x83, 0x96, 0x7e,
	0x46, 0x05, 0x6d, 0x8a, 0xe9, 0xc7, 0x80, 0xc6, 0x69, 0x91, 0xd4, 0x2e, 0xc6, 0xf4, 0xe3, 0x5c,
	0x0b, 0xe4, 0x02, 0x40, 0x89, 0x98, 0x07, 0xef, 0xb1, 0x83, 0xbc, 0xc1, 0xc4, 0x9a, 0x0d, 0x2e,
	0x0e, 0xcf, 0xea, 0x7e, 0xac, 0x9b, 0xcb, 0x77, 0x55, 0xdd, 0x67, 0xdf, 0xc2, 0xa8, 0x5a, 0x47,
	0x28, 0xf4, 0xb6, 0x0d, 0xf5, 0x02, 0xf6, 0x4b, 0xf5, 0x52, 0x8b, 0xe4, 0x1b, 0xb0, 0x7f, 0x4d,
	0x13, 0x9e, 0x7b, 0xfb, 0xfa, 0xad, 0xa3, 0xd5, 0x5b, 0xb1, 0xfb, 0x7c, 0x93, 0x24, 0x5f, 0x82,
	0x93, 0x49, 0x91, 0x4a, 0xa1, 0xee, 0xbd, 0x91, 0xae, 0xbe, 0x8e, 0xb1, 0x76, 0xdd, 0xc3, 0x01,
	0x7e, 0xdb, 0x3b, 0x30, 0xb5, 0x6b, 0x05, 0xeb, 0x22, 0x5f, 0x80, 0xc3, 0x13, 0x66, 0x92, 0x63,
	0x9d, 0xec, 0xf3, 0x84, 0xe9, 0xd4, 0x09, 0xf4, 0x6e, 0x79, 0xc2, 0x52, 0xe9, 0x3d, 0x31, 0x10,
	0x9a, 0xc8, 0x7c, 0x2d, 0xbd, 0x15, 0x8c, 0x4b, 0x8f, 0xe8, 0x4c, 0x1d, 0x63, 0x2e, 0xa4, 0x8a,
	0x2f, 0x52, 0x79, 0xef, 0x1d, 0x9a, 0x5c, 0x15, 0xe3, 0x46, 0x0b, 0xc5, 0x63, 0xef, 0xc8, 0x6c,
	0x34, 0x8e, 0x1b, 0x7c, 0x1e, 0xb7, 0xf3, 0x79, 0xd2, 0xe4, 0xf3, 0x77, 0x1b, 0x9c, 0xd7, 0x22,
	0x0f, 0xf5, 0x2e, 0xfc, 0x67, 0x44, 0x6b, 0x1c, 0xad, 0xc7, 0x70, 0xec, 0x3e, 0x8e, 0xa3, 0xbd,
	0x23, 0x8e, 0xbd, 0x5d, 0x71, 0xec, 0x7f, 0x0a, 0x47, 0xe7, 0x13, 0x38, 0xba, 0xed, 0x38, 0xc2,
	0x67, 0xe2, 0x38, 0x68, 0xc5, 0x71, 0xb8, 0x2b, 0x8e, 0xfb, 0xad, 0x38, 0x8e, 0xda, 0x70, 0x3c,
	0xd8, 0x86, 0xe3, 0x78, 0x2b, 0x8e, 0x4f, 0x5a, 0x70, 0x24, 0x5b, 0x70, 0x3c, 0xdc, 0x8a, 0xe3,
	0x51, 0x3b, 0x8e, 0xc7, 0x4d, 0x1c, 0xff, 0xe8, 0xe2, 0x89, 0x92, 0x2f, 0x6f, 0x68, 0xf8, 0x61,
	0xc7, 0x13, 0xa5, 0x01, 0xa9, 0xf5, 0x00, 0x52, 0x73, 0x8c, 0x86, 0x52, 0x64, 0xfa, 0x18, 0xed,
	0xd6, 0xc7, 0x68, 0x25, 0x6d, 0x47, 0xd0, 0xde, 0x8e, 0xe0, 0xf6, 0xff, 0xeb, 0x43, 0x38, 0xad,
	0x0d, 0x38, 0x37, 0xd9, 0x73, 0xda, 0xd9, 0x73, 0x3f, 0x93, 0x3d, 0x78, 0x8c, 0xbd, 0x46, 0x5b,
	0x98, 0xc3, 0x6a, 0xbd, 0x2d, 0xfe, 0x3f, 0x9c, 0xab, 0x63, 0x77, 0xb4, 0x71, 0xec, 0x6e, 0x62,
	0x71, 0xd0, 0x8e, 0xc5, 0xb8, 0x89, 0xc5, 0x3f, 0x1d, 0x18, 0xce, 0xb3, 0x2c, 0x12, 0x9c, 0x3d,
	0x7e, 0x98, 0x9e, 0x42, 0x1f, 0x4f, 0xf4, 0xd5, 0x5f, 0xaa, 0x87, 0xe1, 0x15, 0xc3, 0x6e, 0xc8,
	0x70, 0xc6, 0x0a, 0x8d, 0xbe, 0x8e, 0xaf, 0xd8, 0xfa, 0x0e, 0x76, 0x37, 0x77, 0xd0, 0xdc, 0x94,
	0x98, 0xfe, 0x53, 0xd9, 0xfa, 0xa6, 0xc4, 0xea, 0x8b, 0x4b, 0x6f, 0xed, 0xe2, 0xf2, 0x14, 0x80,
	0x9a, 0xaa, 0xb0, 0x6a, 0xb3, 0xd3, 0x6e, 0xa9, 0x98, 0x45, 0xad, 0xad, 0xd9, 0x69, 0x5f, 0xb3,
	0xdb, 0x5c, 0xf3, 0xdf, 0x1d, 0x80, 0x1f, 0x73, 0x25, 0x62, 0x7d, 0xd5, 0x23, 0x5f, 0xc3, 0x3e,
	0x0d, 0x55, 0x41, 0xa3, 0x0a, 0x9c, 0x8e, 0x9e, 0x30, 0x34, 0x62, 0xc9, 0xce, 0x4b, 0x78, 0xc2,
	0xca, 0x9f, 0x39, 0xbe, 0xd5, 0x3c, 0xb8, 0xa7, 0x1f, 0x1c, 0xaf, 0x12, 0xe5, 0xc3, 0x2f, 0x60,
	0x58, 0x55, 0xbf, 0x76, 0x25, 0x1b, 0x94, 0xda, 0x25, 0x2e, 0xf0, 0x39, 0x0c, 0x24, 0xbf, 0xa3,
	0x92, 0xe9, 0x7e, 0x28, 0x6d, 0x02, 0x23, 0x61, 0x1b, 0xe0, 0x6d, 0xaa, 0x7c, 0x40, 0xb0, 0xf2,
	0xc7, 0xee, 0x18, 0xe1, 0x8a, 0x91, 0xef, 0xe0, 0xa0, 0x6a, 0xa7, 0x70, 0x49, 0x93, 0x84, 0x47,
	0xa5, 0x7b, 0xa3, 0x52, 0xbe, 0x34, 0xea, 0x0f, 0x2f, 0xdf, 0x7d, 0x1f, 0xd3, 0x85, 0x08, 0xcf,
	0x32, 0xaa, 0x96, 0x34, 0x3d, 0x0b, 0xd3, 0xf8, 0x3c, 0x11, 0x8b, 0xa5, 0xba, 0x13, 0xc9, 0xe2,
	0x5c, 0x5f, 0xc6, 0xeb, 0xbb, 0xf9, 0x4d, 0x4f, 0xc7, 0xaf, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0xba, 0x01, 0x42, 0x11, 0xb7, 0x0b, 0x00, 0x00,
}
